/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./terms.html", "./privacy.html", "./src/**/*.{js,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "#44182b",
        "vibrant-plum": "#6B1D47",
        "soft-plum": "#9E7389",
        "off-white": "#F9FAFB",
        "ice-blue": "#F0F4F8",
        "slate-glass": "#E2E8F0",
        iridescent: "#D8B4FE",
        "inverse-surface": "#31302d",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "on-secondary-fixed-variant": "#52443b",
        "tertiary-fixed": "#f4dfcb",
        "on-surface-variant": "#514347",
        "on-secondary-fixed": "#241911",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "on-primary-fixed-variant": "#6a374b",
        "on-surface": "#1c1c19",
        secondary: "#6b5b51",
        "surface-tint": "#854e63",
        "on-tertiary-container": "#b8a593",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1c19",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#f9b3cb",
        "on-error-container": "#93000a",
        "secondary-fixed": "#f4ded1",
        "on-tertiary-fixed": "#241a0e",
        "primary-container": "#5e2d41",
        "secondary-container": "#f4ded1",
        "surface-container": "#f0ede8",
        surface: "#fcf9f4",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#d7c3b6",
        "outline-variant": "#d5c2c6",
        "tertiary-fixed-dim": "#d7c3b0",
        "error-container": "#ffdad6",
        "on-secondary-container": "#716157",
        outline: "#837377",
        "primary-fixed": "#ffd9e4",
        "surface-dim": "#dcdad5",
        "on-primary-container": "#d795ac",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#f9b3cb",
        "inverse-on-surface": "#f3f0eb",
        "on-tertiary-fixed-variant": "#524436",
        "on-primary-fixed": "#360c1f",
        "surface-bright": "#fcf9f4",
        "surface-variant": "#e5e2dd",
        tertiary: "#312519",
        error: "#ba1a1a",
        background: "#fcf9f4",
        "tertiary-container": "#483b2d",
      },
      fontFamily: {
        headline: ['"Noto Serif"', "ui-serif", "Georgia", "serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        label: ["Manrope", "system-ui", "sans-serif"],
        display: ['"Noto Serif"', "ui-serif", "Georgia", "serif"],
      },
      fontWeight: {
        300: "300",
        400: "400",
        800: "800",
      },
    },
  },
  plugins: [],
};
